name: webordernft
description: "Web Order NFT"

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  http: ^1.2.2
  intl: ^0.19.0

  flutter_form_builder: ^9.4.1
  form_builder_validators: ^11.0.0
  internet_connection_checker_plus: ^2.5.2
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.0.4

  cupertino_icons: ^1.0.8
  file_picker: ^8.1.2
  form_builder_file_picker: ^4.2.0
  filepicker_windows: ^2.1.4
  video_player: ^2.9.1
  responsive_builder: ^0.7.1

  fl_chart: ^0.69.0
  d_chart: ^2.8.0
  data_table_2: ^2.5.15
  timelines: ^0.1.0
  expansion_tile_group: ^2.1.0
  barcode: ^2.2.8
  flutter_quill: ^10.8.5
  printing: ^5.13.4
  path_provider: ^2.1.5
  vsc_quill_delta_to_html: ^1.0.5
  qr_flutter: ^4.1.0
  signature: ^5.5.0
  barcode_widget: ^2.0.4
  htmltopdfwidgets: ^1.0.5
  mime: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
  assets:
    - assets/
    - assets/images/logo/
    - assets/icons/
    - assets/images/banner/
    - assets/video/
    - assets/video/nft.mp4


  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: SFProBold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: SFProSemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
    - family: SFProMedium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: NebulaReg
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Medium.ttf
    - family: arial
      fonts:
        - asset: assets/fonts/arial.ttf    


